# syncview-api 배포용
steps:
  # 1. Dockerfile 빌드
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'asia-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
      - '-f'
      - Dockerfile
      - .
    dir: backend
    id: Build

  # 2. 컨테이너 이미지 푸시
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
    id: Push

  # 3. Cloud Run 서비스로 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=asia-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--cpu=2'
      - '--memory=1Gi'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--timeout=300'
      - '--port=8080'
    id: Deploy
    entrypoint: gcloud

images:
  - 'asia-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'

timeout: 900s

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _DEPLOY_REGION: asia-northeast3
  _SERVICE_NAME: syncview-api

tags:
  - gcp-cloud-build-deploy-cloud-run
  - syncview-api
