steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
      - '-f'
      - backend/Dockerfile
      - backend
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--cpu=2'
      - '--memory=1Gi'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--timeout=300'
      - '--port=8080'
    id: Deploy
    entrypoint: gcloud

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/syncview-api/syncview-api:$COMMIT_SHA'

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: syncview-api

tags:
  - gcp-cloud-build-deploy-cloud-run
  - syncview-api
